{% set version = "0.1.6" %}

package:
  name: fault-localization
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fault-localization/fault-localization-{{ version }}.tar.gz
  sha256: 359cf68d79e4f585f72d7fb7c701f8e39295b349a21b558a63e2b633a4da394a

build:
  number: 1
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=3.1.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - fault_localization

about:
  home: https://github.com/hchasestevens/fault-localization
  license: MIT
  license_family: MIT
  # not included in the sdist: https://github.com/hchasestevens/fault-localization/pull/7
  license_file: ''
  summary: "A fault localization tool for Python's pytest testing framework."
  description: "A fault localization tool for Python's pytest testing framework."

extra:
  recipe-maintainers:
    - nicoddemus
