travis:
  secure:
    BINSTAR_TOKEN: pp6PiySN1h76wEmcZ1+qdRF39PjIhyFAWI89K06JHWhHr5w04o/MYPKS9f1IBCUJgMZ+F1GQfXCn++lUNdUSXSwehNHriE5N8NbzQFVUBX1JKOo6uVxECsAMeg7PPsrx8iVKffazZS0k8thVaEGzIvAoOAJ8QidpAylzbxjP9DBKqg6/pnHr8Lhqovb3M8KD9HWoJYcb6Kf4ldOQ68L1rTXQkIEWBnTLbFaxTsYnjCAQZUsA/cqaYPJBBHr9v66ZSNB77wTQZtBESQb0kWXpwyuVV0ayzONtvmLYkVSYrPenMbmj/qwTs5Qo2FQeFaM3Q9JwTrB14b0kIqzG91OBlkldh8qkgB6ns1EejjcPsVx/w16w1W6Jql9XqLvx0y99FPpSDoH3KQ6xb4NWcRVIuetaE9VbyfCp7MSpuCOAAaGwMfIXArWD/PHiF8uNAmaIyzTgxQVNjpCU9GlDEGum/zvULlEOMOvdVAiQ9zBuAIncS4ufYGztioIa88/8P3hQSPq92SORXyFRzXnC85Qqv7AwOb0NyY/sIO9qizT8fGKE5CGgiCocsj4KPb/BqD9juCyRWYNwp5i9/e0krVqWeQBqcR7ftqO1UEnQNUaGYbM+EacQrejXPISHeqVxryP9fFv8+fAcjKMhE8A1COO77A//snpoMXukKUFl81O8Joc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
