travis:
  secure:
    BINSTAR_TOKEN: jk4ZywmWxJsvshDMfG1n45TykHBVnFYstkcvKKLUTib8dsHteJN4SIECQlD+avUNKoW3tURTGo5i9n+5pzBYft+8VX4Ypcnhw0P2d+O5iaJhf8bhHcLrL3T2eYuR+UksuFqvZXZuGSSWD2xecf7LZhyUa5RnhNT6vcCACTMHg+uKjGPDu0aMp0luXrTI28unT9nbbAPdaUkZW4ASPl0sHacmmg8+yarMjbGudPoSq3g0H/5+3L/0WacvWRiVrDLbG9TIVc9CnUbtCc/lTiaUh+y7UdkB0PGLWzizIRMDOSXBKMnA/13mMsSlckzmAvuGabtWyXxYpjV5cXj+G+uxWfBf1qWyLsWXPJdkkKNroiHdhQeqaJQddt65kM4f6cRJn5RzgTvS3jzsrAdFsLuCqzqMbZbHKUIkXtAd2YlBcIXs75R+6cKFVXwMK3YFK3smul0wQcToF3Igq1TvsMJHOHcgL7ifLoH3ZJxpY3V0RU+52KO9urac2Y70IvCuvctNHeNdpjjhQ4mt/wmsP7sR+ISQP8M2LkUbiX26OH8ffe9+nN6HHpHmD7z0OMGE472JlaQL8xCDXgutfm2xMlTxgecSmd9iY//BA9pcAkXQtTQCUnDW6Ux6mwPfxm3gvCOqPf3poG2jfB2Oka+Ie9WLVYTQ20g2YfDFpZE+FdKmHIA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
